### ISSUE TITLE
Example screenshot?

### ISSUE THREAD

**Issue by legolord208** [andrew-lucker/Lattice#2]
Saw your [dev.to article](https://dev.to/andrewlucker/lattice-30-functional-programming-in-rust), and decided to check this project out. And the first thing I noticed is that having screenshots of one example would make it much easier to see how it could look like and get inspired!

**Comment by andrew-lucker** [comment]
Added one example for text alignment and wrapping. Should probably have 4 or 5 screenshots before closing this issue.

**Comment by legolord208** [comment]
:+1:

**Comment by andrew-lucker** [comment]
Hit 0.4 with a few screenshots. Several more should land soon enough.
