### ISSUE TITLE
units as enum?

### ISSUE THREAD

**Issue by ConnyOnny** [andrew-lucker/Lattice#5]
Why are the units (e.g. "%", "degree") stringly typed? Instead you could have an enum something like this:

```rust
enum SpacingUnit {
    Percent,
    Em,
    Px,
}
enum RotationUnit {
    Degrees,
    Radians,
}
```

(This example doesn't claim completeness)

**Comment by andrew-lucker** [comment]
Units are already implemented by using enums, check [the documentation](https://docs.rs/Lattice/0.3.13/Lattice/view/index.html) to see them all. Optionally the unit types are stringly typed then forced into the enum with an Into<*Unit>. This way users can choose which one they want to use.

In short, I like the stringly typed version, but you are not the first person to ask for typesafe units. So now there is a compromise solution.

**closing** as dup
